services:
  - type: web
    name: maintenance-log
    env: python
    buildCommand: pip install --upgrade pip && pip install -e .
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 main:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DATABASE_URL
        fromDatabase:
          name: maintenance-log-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: maintenance-log-db
    databaseName: maintenance_log
    user: maintenance_log_user